A = {c, f, h}
B = {c, d, e}
A \ B = {f, h}
B \ A = {d, e}
-A = {a, b, d, e, g, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z}
-B = {a, b, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z}
A = {}
A \ B = {}
B \ A = {c, d, e}
-A = {a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z}
-B = {a, b, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z}
