A = {}
B = {}
A \ B = {}
B = {d, j, n, q}
A \ B = {}
B \ A = {d, j, n, q}
A = {c, m}
A \ B = {c, m}
B \ A = {d, j, n, q}
-A = {a, b, d, e, f, g, h, i, j, k, l, n, o, p, q, r, s, t, u, v, w, x, y, z}
-B = {a, b, c, e, f, g, h, i, k, l, m, o, p, r, s, t, u, v, w, x, y, z}
A = {c, d, m, n}
A \ B = {c, m}
B \ A = {j, q}
A = {d, j, n, q}
A \ B = {}
